name: Scrape SCSHOW Cards to CSV

on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * 1" # 毎週月曜 18:15(JST) 実行例。必要に応じて調整

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Playwright Browsers
        uses: microsoft/playwright-github-action@v1

      - name: Install deps
        run: npm ci

      - name: Run scraper
        run: npm run scrape

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scshow-cards-csv
          path: cards.csv
          if-no-files-found: error
