name: Scrape SCSHOW Cards to CSV

on:
  workflow_dispatch:

concurrency:
  group: scrape-scshow-${{ github.ref }}
  cancel-in-progress: false

env:
  CACHE_VERSION: v1
  NPM_CACHE_DIR: ~/.npm

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Prepare cache directories
        shell: bash
        run: |
          set -eux
          mkdir -p "${NPM_CACHE_DIR}"
          mkdir -p ~/.cache/ms-playwright ~/.cache/playwright

      - name: Setup Node
        id: node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Detect lockfile
        id: detect
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then
            echo "lock_exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "lock_exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Cache npm (by package-lock.json)
        if: steps.detect.outputs.lock_exists == 'true'
        id: cache_npm_lock
        uses: actions/cache@v4
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: npm-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-lock-${{ hashFiles('package-lock.json') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            npm-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-lock-
            npm-${{ runner.os }}-

      - name: Cache npm (by package.json)
        if: steps.detect.outputs.lock_exists != 'true'
        id: cache_npm_pkg
        uses: actions/cache@v4
        with:
          path: ${{ env.NPM_CACHE_DIR }}
          key: npm-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-pkg-${{ hashFiles('package.json') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            npm-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-pkg-
            npm-${{ runner.os }}-

      - name: Cache Playwright browsers
        id: cache_pw
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            ~/.cache/playwright
          key: pw-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-${{ hashFiles('package-lock.json', 'package.json') }}-${{ env.CACHE_VERSION }}
          restore-keys: |
            pw-${{ runner.os }}-node${{ steps.node.outputs.node-version }}-
            pw-${{ runner.os }}-

      - name: Debug | System & Cache status (pre-install)
        shell: bash
        run: |
          echo "::group::Runner/Tool versions"
          uname -a || true
          which node && node -v
          which npm && npm -v
          which npx && npx --version || true
          echo "::endgroup::"

          echo "::group::Disk / Memory"
          df -h
          free -h || true
          echo "::endgroup::"

          echo "::group::Cache hits"
          echo "npm cache (lock) hit: ${{ steps.cache_npm_lock.outputs.cache-hit }}"
          echo "npm cache (pkg)  hit: ${{ steps.cache_npm_pkg.outputs.cache-hit }}"
          echo "playwright cache  hit: ${{ steps.cache_pw.outputs.cache-hit }}"
          echo "::endgroup::"

          echo "::group::Existing cache directories (before install)"
          echo "NPM_CACHE_DIR=${NPM_CACHE_DIR}"
          [ -d "${NPM_CACHE_DIR}" ] && du -sh "${NPM_CACHE_DIR}" || echo "NPM cache dir not found"
          for d in ~/.cache/ms-playwright ~/.cache/playwright; do
            if [ -d "$d" ]; then du -sh "$d"; else echo "$d not found"; fi
          done
          echo "::endgroup::"

      - name: Install deps (npm ci/install with detailed logs)
        env:
          npm_config_loglevel: silly
          NODE_OPTIONS: "--trace-deprecation"
        shell: bash
        run: |
          set -euxo pipefail
          echo "::group::npm config"
          npm config set cache "$NPM_CACHE_DIR" --global
          npm config set prefer-offline true
          npm config get cache
          npm config ls -l
          echo "::endgroup::"

          echo "::group::npm ci / install"
          if [ "${{ steps.detect.outputs.lock_exists }}" = "true" ]; then
            echo "package-lock.json found → running npm ci"
            npm ci --prefer-offline --no-audit --fund=false --verbose
          else
            echo "package-lock.json not found → running npm install"
            npm install --prefer-offline --no-audit --fund=false --verbose
          fi
          echo "::endgroup::"

      # Playwright CLI でブラウザ＋システム依存を導入（Ubuntu 24.04対応）
      - name: Install Playwright browsers & system deps (CLI)
        shell: bash
        run: |
          set -euxo pipefail
          PV="$(node -e "try{process.stdout.write(require('@playwright/test/package.json').version)}catch(e){process.stdout.write('')}" || true)"
          if [ -n "$PV" ] && dpkg --compare-versions "$PV" ge "1.51.1"; then
            npx playwright install --with-deps
          else
            npx -y @playwright/test@1.51.1 playwright install --with-deps
          fi

      - name: Debug | Post-install snapshot
        shell: bash
        run: |
          echo "::group::node_modules size & key files"
          du -sh node_modules || true
          test -f package-lock.json && sha256sum package-lock.json || true
          sha256sum package.json || true
          echo "::endgroup::"

          echo "::group::Cache directories (after install)"
          [ -d "${NPM_CACHE_DIR}" ] && du -sh "${NPM_CACHE_DIR}" || echo "NPM cache dir not found"
          for d in ~/.cache/ms-playwright ~/.cache/playwright; do
            if [ -d "$d" ]; then du -sh "$d"; else echo "$d not found"; fi
          done
          echo "::endgroup::"

      # --- 失敗時の診断用ヘルパーをその場で作成（URLは環境に合わせて必要なら設定） ---
      - name: Create failure diagnostic helper
        shell: bash
        run: |
          mkdir -p tools artifacts
          cat > tools/pw-dump-on-fail.js <<'EOF'
          const fs = require('fs');
          const path = require('path');
          const { chromium } = require('playwright');
          (async () => {
            const url = process.env.DUMP_URL || 'about:blank';
            const outDir = process.env.DUMP_DIR || 'artifacts';
            fs.mkdirSync(outDir, { recursive: true });
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();
            try {
              await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 30000 }).catch(()=>{});
              await page.waitForTimeout(2000);
              await page.screenshot({ path: path.join(outDir, 'fail-screenshot.png'), fullPage: true }).catch(()=>{});
              const html = await page.content();
              fs.writeFileSync(path.join(outDir, 'fail-page.html'), html);
            } catch (e) {
              fs.writeFileSync(path.join(outDir, 'dump-error.txt'), String(e.stack || e));
            } finally {
              await browser.close();
            }
          })();
          EOF

      # --- スクレイパー実行（最大3回まで再試行） ---
      - name: Run scraper (up to 3 attempts)
        shell: bash
        env:
          # Playwright のAPIログを詳細化（コンソールに出力）
          DEBUG: pw:api
          # ダンプ対象URL（必要なら設定、未設定でもOK）
          DUMP_URL: ""
        run: |
          set -euxo pipefail
          attempt=1
          max=3
          until [ $attempt -gt $max ]; do
            echo "::group::Attempt $attempt / $max"
            if npm run scrape; then
              echo "Success on attempt $attempt"
              echo "::endgroup::"
              break
            fi
            echo "Attempt $attempt failed. Waiting and retrying..."
            echo "::endgroup::"
            attempt=$((attempt+1))
            sleep 7
          done

          if [ $attempt -gt $max ]; then
            echo "All attempts failed. Capturing diagnostics..."
            node tools/pw-dump-on-fail.js || true
            exit 1
          fi

      - name: Verify output
        shell: bash
        run: |
          set -euo pipefail
          test -f cards.csv
          wc -l cards.csv || true
          head -n 20 cards.csv || true

      - name: Upload npm logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: npm-logs
          path: ~/.npm/_logs/
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload diagnostics (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: |
            artifacts/**
            tools/pw-dump-on-fail.js
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scshow-cards-csv
          path: cards.csv
          if-no-files-found: error
